In [4]:
import numpy as np

In [1]:
ll = [
    [1,2,3],[4,5,6],[7,8,9]
]

In [5]:
m3x3 = np.array(ll)

In [7]:
type(m3x3)

numpy.ndarray

In [8]:
m3x3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
m3x3.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [10]:
m3x1 = np.array([[10,20,0]])

In [11]:
m3x3 * m3x1

array([[ 10,  40,   0],
       [ 40, 100,   0],
       [ 70, 160,   0]])

In [12]:
np.sin(m3x3)

array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ],
       [ 0.6569866 ,  0.98935825,  0.41211849]])

In [13]:
m3x3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
m3x3[1:,:2]

array([[4, 5],
       [7, 8]])

In [23]:
list_1 = [
    [10,20,30],
    [40,50,60],
    [70,80,90]
]

In [24]:
m_1 = np.array(list_1)

In [25]:
m_2 = m_1 * 0.333

In [26]:
m_2

array([[ 3.33,  6.66,  9.99],
       [13.32, 16.65, 19.98],
       [23.31, 26.64, 29.97]])

In [27]:
m_3 = m_1 + m_2

In [29]:
m_3

array([[ 13.33,  26.66,  39.99],
       [ 53.32,  66.65,  79.98],
       [ 93.31, 106.64, 119.97]])